name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: 18
  PERCY_PARALLEL_NONCE: ${{ github.run_id }}-${{ github.run_number }}
  PERCY_PARALLEL_TOTAL: 1

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: npm
      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint


  run-tests:
    name: Test Ember app
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: npm
      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npx percy exec -- npm test
        env:
          PERCY_PARALLEL_NONCE: ${{ env.PERCY_PARALLEL_NONCE }}
          PERCY_PARALLEL_TOTAL: ${{ env.PERCY_PARALLEL_TOTAL }}
          PERCY_TOKEN: cd5bc5477b9709815c49024b91e3e919e2f3eed95f0ddbd8894b7cf01bb19e4b
